name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'apps.json'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: apps.json
          generateReleaseNotes: false
          tag: v${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          skipIfReleaseExists: true
